name: 'Get latest tags'
description: 'Takes an array of repository names and outputs a json with the latest tag of each repository'
inputs:
  githubToken:
    description: 'Github token'
    required: true
  repositories:
    description: 'Array of repository names'
    required: true
    default: '[]'
  repositoryOwner:
    description: 'Owner of the repositories'
    required: true
  branch:
    description: 'Branch to check for tags'
    default: 'main'
outputs:
  latestTags:
    description: 'Stringified JSON with the latest tag of each repository'
runs:
  using: 'node16'
  main: '../lib/get-latest-tags/index.js'