name: 'Get latest tags'
author: Aizon.ai
description: 'Takes an array of repository names and outputs a json with the latest tag of each repository'
inputs:
  token:
    description: 'Github token'
    required: true
  repositories:
    description: 'Repository names separated by comma (,)'
  owner:
    description: 'Owner of the repositories'
    default: ${{ github.repository_owner }}
    required: true
  branch:
    description: 'Branch to check for tags'
    default: 'main'
    required: true
outputs:
  latestTags:
    description: 'JSON with the latest tag of each repository'
runs:
  using: 'node16'
  main: 'index.js'