name: 'Get latest tags'
author: Aizon.ai
description: 'Takes an array of repository names and outputs a json with the latest tag of each repository'
inputs:
  token:
    description: 'Github token'
    required: true
  repositories:
    description: 'Array of repository names'
    required: true
    default: '[]'
  owner:
    description: 'Owner of the repositories'
    required: true
  branch:
    description: 'Branch to check for tags'
    default: 'main'
outputs:
  latestTags:
    description: 'JSON with the latest tag of each repository'
runs:
  using: 'node16'
  main: '../dist/get-latest-tags/index.js'