name: 'Get latest matching tag'
author: Aizon.ai
description: 'Gets the latest tag matching the prefix input and outputs its name'
inputs:
  token:
    description: 'Github token'
    required: true
  repository:
    description: 'Repository name'
    default: ${{ github.event.repository.name }}
  owner:
    description: 'Owner of the repository'
    default: ${{ github.repository_owner }}
  prefix:
    description: 'Prefix to match the tag against'
outputs:
  tag:
    description: 'Name of the latest tag matching the prefix input if any'
runs:
  using: 'node16'
  main: 'index.js'